#include <stdio.h>
#include <assert.h>

// File generated by --header switch inside the nimcache directory.
#include "test_c_api.h"

const char *valid_rst_filename = "temp_good.rst";
const char *bad_rst_filename = "temp_bad.rst";

char valid_rst_string[] = "Embedded *rst* text";
char bad_rst_string[] = "Asterisks and Obelix\n"
	"====================\n"
	"\n"
	"These asterisks* are bad for rst.\n"
	"\n"
	"* Not that we really care.\n"
	"\n"
	// The underscore will be replaced at runtime!
	"Or was <B it _single quotes?";

// Entry point of the C test.
void run_c_test(void)
{
	// Due to backticks being escaped in Nimrod's emit pragma (see
	// https://github.com/Araq/Nimrod/issues/1588) we have to modify
	// bad_rst_string at runtime to avoid it being escaped during Nimrod's C
	// codegen phase.
	assert(strchr(bad_rst_string, '_'));
	*strchr(bad_rst_string, '_') = 0x60;

	// Generates files with rst content.
	{
		FILE *file = fopen(valid_rst_filename, "w+");
		assert(file);
		fwrite(valid_rst_string, 1, sizeof(valid_rst_string), file);
		fclose(file);

		file = fopen(bad_rst_filename, "w+");
		assert(file);
		fwrite(bad_rst_string, 1, sizeof(bad_rst_string), file);
		fclose(file);
	}

	printf("Using lazy_rest %s.\n", lr_version_str());

	int major = 6, minor = 6, maintenance = 6;
	lr_version_int(&major, &minor, &maintenance);
	printf("Using lazy_rest: %d-%d-%d.\n",
		major, minor, maintenance);

	// Tests unsafe string conversions.
	{
		char *s = lr_rst_string_to_html(valid_rst_string,
			"<string>", 0);
		assert(0 != s);
		if (s) {
			// Success!
			assert(strstr(s, "<title>"));
		} else {
			// Handle error.
		}
	}

	{
		char *s = lr_rst_string_to_html(bad_rst_string,
			"<bad-string>", 0);
		assert(0 == s);
		if (!s) {
			// Handle error.
			printf("Ignore the next error message, it's expected\n");
			printf("Error processing string: %s\n",
				lr_rst_string_to_html_error());
		}
	}

	// Tests unsafe file conversions.
	{
		char *s = lr_rst_file_to_html(valid_rst_filename, 0);
		assert(0 != s);
		if (s) {
			// Success!
		} else {
			// Handle error.
		}
	}

	{
		char *s = lr_rst_file_to_html(bad_rst_filename, 0);
		assert(0 == s);
		if (!s) {
			// Handle error.
			printf("Ignore the next error message, it's expected\n");
			printf("Error processing file: %s\n",
				lr_rst_file_to_html_error());
		}
	}

	// Test the safe string conversions.
	{
		char *s = lr_safe_rst_string_to_html(
			"<filename>", valid_rst_string, 0, 0);
		assert(s);
		assert(strstr(s, "<title>"));
		int errors = 1;
		s = lr_safe_rst_string_to_html(
			"<filename>", valid_rst_string, &errors, 0);
		assert(0 == errors);
		if (s) {
			// Success!
		} else {
			// Handle error.
		}
	}

	{
		char *s = lr_safe_rst_string_to_html(
			"<filename>", bad_rst_string, 0, 0);
		assert(s);
		assert(strstr(s, "<title>"));
		int errors = 0;
		s = lr_safe_rst_string_to_html(
			"<filename>", bad_rst_string, &errors, 0);
		assert(errors > 0);
		if (errors) {
			// Handle error.
			printf("Ignore the next error message, it's expected\n");
			printf("RST error stack trace:\n");
			while (errors) {
				printf("\t%s\n",
					lr_safe_rst_string_to_html_error(--errors));
			}
		}
	}


}
