#include <stdio.h>

// File generated by --header switch inside the nimcache directory.
#include "test_c_api.h"

// Entry point of the C test.
void run_c_test(void)
{
	printf("Testing C API for lazy_rest %s.\n", lr_version_str());

	int major = 6, minor = 6, maintenance = 6;
	lr_version_int(&major, &minor, &maintenance);
	printf("Integer versions: %d-%d-%d.\n", major, minor, maintenance);
}
